# -*- coding: utf-8 -*-
"""DeteccaoObjetos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zc88ZphBueBN555aBW9kk1nAuNGpY7AS
"""

import os
import cv2
import numpy as np
import pandas as pd
import os


MODEL_CONFIG = "MobileNetSSD_deploy.prototxt"
MODEL_WEIGHTS = "MobileNetSSD_deploy.caffemodel"
CLASSES = ["background","aeroplane","bicycle","bird","boat", "bottle", "bus",
           "car", "cat", "chair", "cow", "dinigtable", "dog", "horse", "motorbike", "person",
           "pottedplant","sheep","sofa","train","tvmonitor"]

net = cv2.dnn.readNetFromCaffe(MODEL_CONFIG,MODEL_WEIGHTS)



def detect_person_in_video(video_path):
  cap = cv2.VideoCapture(video_path)
  frame_count = 0
  while True:
    ret, frame = cap.read()
    if not ret:
      print("Fim do vídeo ou erro de leitura")
      break
    frame_count += 1
    (h,w) = frame.shape[:2]
    blob = cv2.dnn.blobFromImage(frame, 0.007843, (300,300), 127.5)
    net.setInput(blob)
    detections = net.forward()

    for i in range(detections.shape[2]):
      confidence = detections[0,0,i,2]
      if confidence > 0.7:
        idx = int(detections[0,0,i,1])
        if CLASSES[idx] == "person":
          box = detections[0,0,i,3:7] * np.array([w,h,w,h])
          (startX, startY, endX, endY) = box.astype("int")

          label  = f"{CLASSES[idx]}: {confidence * 100:.2f}%"
          cv2.rectangle(frame, (startX,startY),(endX, endY),(0,255,0),2)
          cv2.putText(frame, label, (startX, startY-10), cv2.FONT_HERSHEY_SIMPLEX, 0.5,(0,255,0),2)
          print(f"Pessoa Detectada no Frame {frame_count}")
          cv2.imshow("Frame", frame)
          cv2.waitKey(0)
          cv2.destroyAllWindows()

          detected_frame_path = f"detected_frame_{frame_count}.jpg"
          cv2.imwrite(detected_frame_path, frame)
          print(f"Frame salvo como {detected_frame_path}")

          cap.release()
          return "Pessoa detectada no vídeo"
  cap.release()
  return "Nenhuma pessoa detectada no vídeo"

def detect_persons_in_video(video_path):
    cap = cv2.VideoCapture(video_path)
    frame_count = 0
    dados = []

    while True:
        ret, frame = cap.read()

        if not ret:
            break

        frame_count += 1
        (h, w) = frame.shape[:2]

        blob = cv2.dnn.blobFromImage(frame, 0.007843, (300,300), 127.5)
        net.setInput(blob)
        detections = net.forward()

        pessoas_no_frame = 0
        confiancas = []

        for i in range(detections.shape[2]):
            confidence = detections[0,0,i,2]

            if confidence > 0.5:
                idx = int(detections[0,0,i,1])

                if CLASSES[idx] == "person":
                    pessoas_no_frame += 1
                    confiancas.append(float(confidence))

                    box = detections[0,0,i,3:7] * np.array([w,h,w,h])
                    (startX, startY, endX, endY) = box.astype("int")

                    cv2.rectangle(frame, (startX,startY),(endX,endY),(0,255,0),2)

        if pessoas_no_frame > 0:
            print(f"{video_path} → Frame {frame_count}: {pessoas_no_frame} pessoa(s)")

            dados.append({
                "video": video_path,
                "frame": frame_count,
                "quantidade_pessoas": pessoas_no_frame,
                "media_confianca": np.mean(confiancas) if confiancas else 0
            })

            cap.release()
            return dados

    cap.release()
    return dados  


dados_totais = []

videos = ["pessoa.mp4","pessoas.mp4"]

for video in videos:
   dados = detect_persons_in_video(video)
   dados_totais.extend(dados)

df = pd.DataFrame(dados_totais)
df.to_csv("dados_gerais.csv", index = False)

#print(detect_person_in_video("pessoa.mp4"))


#print(detect_persons_in_video("mulher.mp4"))
